
name: Build & Push Docker Container
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
      
    - name: Build & Push Backend Image
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ./backend
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}_backend:latest
        cache-to: type=inline
        tags: ghcr.io/${{ github.repository }}_backend:latest

    - name: Build & Push Frontend Image
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ./frontend
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}_frontend:latest
        cache-to: type=inline
        tags: ghcr.io/${{ github.repository }}_frontend:latest

